name: A Meandering Mammoth
favicon: null
layout_spectrum: 0.93665
typography_spectrum: 0.53319
title: 'For Science!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#150800'
    - '#4f5962'
    - '#a9c5d0'
    - '#b68b61'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.125
  rhythmicContrast: 0
purpose:
  - name: null
    item: null
    url: null
