name: A Meandering Mammoth
favicon: null
layout_spectrum: 0.414473
typography_spectrum: 0.325657
title: 'For Science!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8D0D0'
    - '#381000'
    - '#A05050'
    - '#C02830'
    - '#F04858'
  brandStrength: 0.793585
  lightness: 0.731907
  saturation: 0.857975
  rhythmicContrast: 0.834701
purpose:
  - name: null
    item: null
    url: null
