analytics: {}
color:
  brandColors:
    - '#B8D0D0'
    - '#381000'
    - '#A05050'
    - '#C02830'
    - '#F04858'
  brandStrength: 0.793585
  lightness: 0.731907
  rhythmicContrast: 0.834701
  saturation: 0.857975
cta: {}
layout_spectrum: 0.414473
name: A Meandering Mammoth
opengraph: {}
purpose: {}
typography_spectrum: 0.325657
